version: '1.0'
services:
  my-api-services:
    container_name: my-api-cont
    image: my-api
    build: .
    ports:
      - "8000:8080"
    
  my-db-services:
    image: postgres:17.4-alpine3.21
    container_name: my-db-cont
    ports:
      - "5439:5432"
    command: postgres -c max_wal_senders=2 -c wal_level=logical -c max_replication_slots=2
    environment:
      - POSTGRES_USER=ronishg
      - POSTGRES_PASSWORD=rons
      - POSTGRES_DB=tododb

    